version: '3'

services:

  client:
    image: node:16
    hostname: client
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"